# Example configuration file for Mosquitto

# Allow anonymous connections
#allow_anonymous true
password_file /mosquitto/config/passwordfile
allow_anonymous false

# Define listeners
listener 1883
listener 8883

# Log file and level
log_dest file /mosquitto/log/mosquitto.log
log_type all
log_dest stdout
log_type error

# Persistent storage
persistence true
persistence_location /mosquitto/data/mosquitto.db
